language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
script: bundle exec rake
rvm:
- 1.9.3
- 2.0.0
- 2.1
- 2.2
- 2.3.0
- ruby-head
- rbx-2
- jruby-19mode
- jruby-head
bundler_args: "--path vendor/bundle"
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: degxppatinj2DhFXR2j6QqcmjihZ7sVWq66iwjQqUd3QE1RJfjVRiL6XnBGOjG9y674cWrHqqvvk/nmGV0Aw9x6eh3FVOy6bf2Ug29FKPqeV4ze/AqkE74Qk5N+3ebdMzeqY2SsH1CUjtOBnOZpHnFSCMZvY5lr9yQYnHMm6r28=
  gem: redis-store
  on:
    tags: true
    repo: redis-store/redis-store
